//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cometidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleados()
        {
            this.Cometidos = new HashSet<Cometidos>();
            this.Estudios = new HashSet<Estudios>();
        }
    
        public string Rut { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public System.DateTime Fecha_nacimiento { get; set; }
        public string Sexo { get; set; }
        public string Civil { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public int Grado { get; set; }
        public int IdVinculo_FK { get; set; }
        public int IdEscalafon_FK { get; set; }
        public int IdDepartamento_FK { get; set; }
        public string Cargo { get; set; }
        public int IdIsapre_FK { get; set; }
        public int IdAfp_FK { get; set; }
        public System.DateTime Fecha_inic_contrato { get; set; }
        public System.DateTime Fecha_fin_contrato { get; set; }
    
        public virtual Afp Afp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cometidos> Cometidos { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual Escalafon Escalafon { get; set; }
        public virtual Isapre Isapre { get; set; }
        public virtual Vinculo Vinculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estudios> Estudios { get; set; }
    }
}
