//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cometidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudios
    {
        public int IdEstudios { get; set; }
        public string Rut_fk { get; set; }
        public int Nivel { get; set; }
        public string Titulo { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}
