//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cometidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValoresViaticos
    {
        public int IdValores { get; set; }
        public int RanMin { get; set; }
        public int RanMax { get; set; }
        public int Valor { get; set; }
    }
}
